services:
  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"

  rabbitmq:
    image: rabbitmq:3-management
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  source_crawler:
    build:
      context: .
      dockerfile: services/source_crawler/Dockerfile
    working_dir: /app
    volumes:
      - ./common_utils:/app/common_utils
      - ./services/source_crawler:/app/service
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      LOG_LEVEL: ${LOG_LEVEL}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      CRAWLER_INTERVAL_SECONDS: ${CRAWLER_INTERVAL_SECONDS}
      PYTHONPATH: /app
    depends_on:
      rabbitmq:
        condition: service_healthy

  core_engine:
    build:
      context: .
      dockerfile: services/core_engine/Dockerfile
    working_dir: /app
    volumes:
      - ./common_utils:/app/common_utils
      - ./services/core_engine:/app/service
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      LOG_LEVEL: ${LOG_LEVEL}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      PYTHONPATH: /app
    depends_on:
      - mysql
      - rabbitmq



  test:
    build:
      context: .
      dockerfile: services/source_crawler/Dockerfile
    command: >-
      sh -c "pip install -r requirements-dev.txt && coverage run -m pytest && coverage xml"
    volumes:
      - .:/app
    environment:
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DB: ${MYSQL_DB}
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      RABBITMQ_USER: ${RABBITMQ_USER}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: 5672
      LOG_LEVEL: ${LOG_LEVEL}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      GOOGLE_PROJECT_ID: ${GOOGLE_PROJECT_ID}
      CRAWLER_INTERVAL_SECONDS: ${CRAWLER_INTERVAL_SECONDS}
    depends_on:
      - mysql
      - rabbitmq
