name: RoboPost CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-asyncio
        # Install dependencies for each service
        pip install -r services/api_gateway/requirements.txt
        pip install -r services/source_fetcher/requirements.txt
        # ... and so on for other services

    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    # Note: Full integration testing requires docker-compose.test.yml to be fully configured
    # - name: Run Tests with Pytest
    #   run: |
    #     # Setup environment for testing (e.g., start docker-compose.test.yml)
    #     # docker-compose -f docker-compose.test.yml up -d
    #     pytest
    #     # docker-compose -f docker-compose.test.yml down