name: RoboPost CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: test_password
          MYSQL_DATABASE: test_db
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      rabbitmq:
        image: rabbitmq:3.11-management
        ports:
          - 5672:5672

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install All Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ./shared/models
        for req in services/*/requirements.txt; do pip install -r "$req"; done
        pip install flake8 pytest pytest-asyncio pytest-cov

    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run Tests with Pytest
      run: |
        pytest --cov=services --cov-report=xml
      env:
        # Set environment variables for the test run
        DATABASE_URL: "mysql+aiomysql://test_user:test_password@localhost:3306/test_db"
        RABBITMQ_URL: "amqp://guest:guest@localhost:5672/"
        # Add other necessary env vars for testing here